mbit(3주차~)/backend/mbitTest/MBIT/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

mbit(3주차~)/backend/mbitTest/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('form/', views.form, name='form'),
    path('submit/', views.submit, name='submit'),
    path('result/<int:developer_id>/', views.result, name='result'),
    path('all_results/', views.all_results, name='all_results'),
]

mbit(3주차~)/backend/mbitTest/main/models.py
from django.db import models

# Create your models here.
class Developer(models.Model):
    name = models.CharField(max_length=50)
    count = models.IntegerField(default=0)
    data = models.JSONField()
    
    def __str__(self):
        return self.name
    
class Question(models.Model):
    number = models.IntegerField(unique = True)
    content = models.CharField(max_length = 100)
    
    def __str__(self):
        return f'{self.number}. {self.content}'
    
class Choice(models.Model):
    content = models.CharField(max_length = 100)
    question = models.ForeignKey(to = 'main.Question', on_delete = models.CASCADE)
    developer = models.ForeignKey(to = 'main.developer', on_delete = models.CASCADE, null = True)
    
    def __str__(self):
        return self.content

mbit(3주차~)/backend/mbitTest/main/views.py
from django.shortcuts import render, redirect
from .models import Question, Developer, Choice

def index(request):
    developers = Developer.objects.all()
    
    context = {
        'developers': developers,
    }
    
    return render(request, 'main/index.html', context=context)

def form(request):
    questions = Question.objects.all()
    
    context = {
        'questions': questions,
    }
    
    return render(request, 'main/form.html', context)

def submit(request):
    
    N = Question.objects.count()
    K = Developer.objects.count()
    
    counter = [0] * (K + 1)
    
    for n in range(1, N+1):
        developer_id = int(request.POST[f'question-{n}'][0])
        counter[developer_id] += 1
    
    # 최고점 개발 유형
    best_developer_id = max(range(1, K + 1), key=lambda id: counter[id])
    best_developer = Developer.objects.get(pk=best_developer_id)
    best_developer.count += 1
    best_developer.save()
    
    context = {
        'developer': best_developer,
        'counter': counter
    }
    
    return redirect('main:result', developer_id=best_developer_id)

def result(request, developer_id):
    developer = Developer.objects.get(pk=developer_id)
    context = {
        'developer': developer,
    }
    return render(request, 'main/result.html', context=context)

def all_results(request):
    return render(request, 'main/all_results.html')

mbit(3주차~)/backend/mbitTest/main/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
	<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
	<script type="text/javascript" src="{% static 'js/form.js' %}"></script>
    <title>나의 개발 유형찾기</title>
</head>
<body>
    <section id="survey">
        <div class="wrapper">
            <form id="form" action="/result/" method = "post">
                {% csrf_token %}
                {% for question in questions %}
                <div class="test">
                    <div class="question_container">
                        <h3 class="number">{{ question.number }}/{{ questions.count }}</h3>
                        <h3 class="question">{{ question.content }}</h3>
                    </div>
                    <div class="answer">
                        {% for choice in question.choice_set.all %}
                        <div>
                            <input 
                                   type="radio" 
                                   name="question-{{ question.number }}" 
                                   id="choice-{{ choice.pk }}" 
                                   value="{{ choice.developer.pk }}"
                            />
                            <label for="choice-{{ choice.pk }}">
                                {{ forloop.counter }}. {{ choice.content }}
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                    {% if not forloop.first %}
                        <div class="btn_wrap btn_sort">
                    {% else %}
                        <div class = "btn_wrap">
                    {% endif %}
                    {% if not forloop.first %}
                        <button class="prev_btn">이 전</button>
                    {% endif %}
                    {% if not forloop.last %}
                        <button class="next_btn">다 음</button>
                    {% else %}
                        <input type="submit" value="제 출" class="submit_btn"/>
                    {% endif %}
                    </div>
                </div>
            {% endfor %}
            </form>
        </div>
    </section>
</body>
</html>

mbit(3주차~)/backend/mbitTest/main/templates/form_back.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>form</title>
</head>
<body>
  <form action="/result/" method="post">
    {% csrf_token %}
    {% for question in questions %}
      <h3>{{ question.number }}번 {{ question.content }}</h3>
      {% for choice in question.choice_set.all %}
        <div>
          <input type="radio" name="question-{{ question.number }}" id="choice-{{ choice.pk }}" value="{{ choice.developer.pk }}">
          <label for="choice-{{ choice.pk }}">{{ forloop.counter }}. {{ choice.content }}</label>
        </div>
      {% endfor %}
      <hr>
    {% endfor %}
    <input type="submit" value="제출하기">
  </form>
</body>
</html>

mbit(3주차~)/backend/mbitTest/main/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>나의 개발 유형찾기</title>
</head>
<body> 
    <section id="main_contents">
        <div class="wrapper">
            <div class="title">
                <h3 class="main_title">나의 MBIT</h3>
                <h3 class="sub_title">My Best IT personalities</h3>
            </div>
            <div class="explain">
                <p>
                    "코딩 공부를 시작하려는데...<br>
                    도대체 뭐 부터 공부해야 할까?"<br><br>
                    나의 개발 유형을 테스트 해보자!
                </p>
            </div>
            <div class="buttons">
                <a href="/form/">
                    <button class="start" type="button">시작하기</button>
                </a>
                <a href="http://www.paullab.co.kr/curriculum.html" target="_blank">
                    <button class="lecture">강의 보러가기</button>
                </a>
            </div>
            <div class="result_data">
                <div class="data_wrap">
                    <ul>
                        {% for developer in developers %}
                            <li>{{ developer.name }} : {{ developer.count }}명</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="weniv">
                <a href="http://www.paullab.co.kr">
                    <img src="{% static 'img/weniv_text_logo.png' %}" alt="weniv">
                </a>
            </div>
        </div>
    </section>
</body>
</html>

mbit(3주차~)/backend/mbitTest/main/templates/main/all_results.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all_results.css' %}">
    <title>나의 개발 유형찾기</title>
{% endblock head %}


{% block body %}
    <section id="main_contents">
        <div class="wrapper">
            <h1>MBIT</h1>
            <div class="mbit">
                <div class="frontend">
                    <a href="/result/2"><img src="{% static 'img/frontend-no-bg.png' %}" alt="프론트엔드"></a>
                </div>
                <div class="backend">
                    <a href="/result/1"><img src="{% static 'img/backend-no-bg.png' %}" alt="백엔드"></a>  
                </div>
                <div class="security">
                    <a href="/result/4"><img src="{% static 'img/information_security-no-bg.png' %}" alt="정보보안"></a>
                </div>
                <div class="game">
                    <a href="/result/5"><img src="{% static 'img/game_developer-no-bg.png' %}" alt="게임개발"></a>
                </div>
                <div class="data">
                    <a href="/result/3"><img src="{% static 'img/data_analyst-no-bg.png' %}" alt="데이터분석"></a>
                </div>
            </div>
        </div>
    </section>
{% endblock body %}

mbit(3주차~)/backend/mbitTest/main/templates/main/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>나의 개발 유형찾기 - final</title>
    {% block head %}
    {% endblock head %}
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock body %}

    {% block js %}
    {% endblock js %}
</body>
</html>

mbit(3주차~)/backend/mbitTest/main/templates/main/form.html
{% extends 'main/base.html' %}

{% load static %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
{% endblock head %}

{% block body %}
    <section id="survey">
        <div class="wrapper">
            <form id="form" action="{% url 'main:submit' %}" method="post">
                {% csrf_token %}
                {% for question in questions %}
                <div class="test">
                    <div class="question_container">
                        <h3 class="number">{{ question.number }}/{{ questions.count }}</h3>
                        <h3 class="question">{{ question.content }}</h3>
                    </div>
                    <div class="answer">
                        {% for choice in question.choice_set.all %}
                        <div>
                            <input
                                type="radio"
                                name="question-{{ question.number }}"
                                id="choice-{{ choice.pk }}"
                                value="{{ choice.developer.pk }}"
                            />
                            <label for="choice-{{ choice.pk }}">
                                {{ forloop.counter }}. {{choice.content}}
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                    {% if not forloop.first %}
                        <div class="btn_wrap btn_sort">
                    {% else %}
                        <div class="btn_wrap">
                    {% endif %}
                    {% if not forloop.first %}
                        <button class="prev_btn">이 전</button>
                    {% endif %}
                    {% if not forloop.last %}
                        <button class="next_btn">다 음</button>
                    {% else %}
                        <input type="submit" value="제 출" class="submit_btn">
                    {% endif %}
                    </div>
                </div>
                {% endfor %}
            </form>
        </div>
    </section>
{% endblock body %}
        
{% block js %}
    <script type="text/javascript" src="{% static 'js/form.js' %}"></script>
{% endblock js %}

mbit(3주차~)/backend/mbitTest/main/templates/main/form_back.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>form</title>
</head>
<body>
  <form action="/result/" method="post">
    {% csrf_token %}
    {% for question in questions %}
      <h3>{{ question.number }}번 {{ question.content }}</h3>
      {% for choice in question.choice_set.all %}
        <div>
          <input type="radio" name="question-{{ question.number }}" id="choice-{{ choice.pk }}" value="{{ choice.developer.pk }}"/>
          <label for="choice-{{ choice.pk }}">{{ forloop.counter }}. {{ choice.content }}</label>
        </div>
      {% endfor %}
      <hr>
    {% endfor %}
    <input type="submit" value="제출하기">
  </form>
</body>
</html>

mbit(3주차~)/backend/mbitTest/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock head %}


{% block body %}
    <section id="main_contents">
        <div class="wrapper">
            <div class="title">
                <h3 class="main_title">나의 MBIT</h3>
                <h3 class="sub_title">My Best IT personalities</h3>
            </div>
            <div class="intro">
                <h1>나의 개발 유형은?!</h1>
                <div class="type">
                    <ul class="type_list">
                        <li>개발자</li>
                        <li>데이터 분석과 인공지능</li>
                        <li>정보보안</li>
                        <li>게임 개발</li>
                        <li>개발자</li>
                    </ul>
                </div>
            </div>
            <div class="button">
                <a href="{% url 'main:form' %}">
                    <button class="start" type="button">시작하기</button>
                </a>     
                <!-- <a href="http://www.paullab.co.kr/curriculum.html" target="_blank">
                    <button class="lecture">강의 보러가기</button>
                </a> -->
            </div>
            <div class="result_data">
                <div class="data_wrap">
                    <ul>
                        {% for developer in developers %}
                            <li>{{ developer.name }} : {{ developer.count }}명</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="weniv">
                <a href="http://www.paullab.co.kr">
                    <img src="{% static 'image/weniv_logo_black.png' %}" alt="weniv">
                </a>
            </div>
        </div>
    </section>
{% endblock body %}

mbit(3주차~)/backend/mbitTest/main/templates/main/index_back.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>index</title>
</head>
<body>
  <h1>index 페이지입니다</h1>
  <a href="form/">설문 하기</a>
  {% for developer in developers %}
    <p>{{ developer.name }} : {{ developer.count }}명</p>
  {% endfor %}
</body>
</html>

mbit(3주차~)/backend/mbitTest/main/templates/main/result.html
{% extends 'main/base.html' %}

{% load static %}

{% block head %}
    <meta property="og:title" content="나의 개발 유형은?" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:description" content="나에게 꼭 맞는 개발 유형은 무엇일까?" />

    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/result.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
{% endblock head %}

{% block body %}
    <section id="main_contents">
        <div class="wrapper">
            <div class="result">
                <div class="titles">
                    <h3>{{ developer.data.title }}</h3>
                    <h1>{{ developer.name }}</h1>
                </div>
                <div class="result_img">
                    <img src="{% static 'image/' %}{{ developer.pk }}.png" alt="frontend">
                </div>
            </div>
            <div class="result_explains">
                <div class="explain">
                    <h3 class="title">나와 맞는 개발 유형은 {{ developer.name }}?!</h3>
                    <ul>
                        {% for feature in developer.data.features %}
                        <li>
                            {{ feature }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="explain">
                    <h3 class="title">{{ developer.name }}(이)가 뭐지?</h3>
                    <ul>
                        {% for description in developer.data.descriptions %}
                            <li>
                                {{ description }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="explain">
                    <h3 class="title">그래서 어떤 언어부터 공부해야 할까?</h3>
                    <ul class="language_lists">
                        {% for language in developer.data.languages.list %}
                        <li>
                            <div class="img_wrap">
                                <img src="{% static '' %}{{ language.img }}" width='200px' alt="{{ language.name }}">
                            </div>
                            <h3>{{ language.name }}</h3>
                        </li>
                        {% endfor %}
                    </ul>
                    {% if data.languages.comments %}
                    <ul>
                    {% for comment in developer.data.languages.comments %}
                        <li>
                            {{ comment }}
                        </li>
                    {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            <div class="lectures">
                <h3 class="title">강의 추천</h3>                
                <p>{{ developer.name }} 공부를 시작하기 좋은 강의를 추천해 드릴게요!</p>
                <ul>
                    {% for lecture in data.lectures %}
                        <li>
                            <a href="{{ lecture.url }}" target="_blank">
                                <img src="{% static '' %}{{ lecture.img }}" alt="{{ developer.lecture.name }}">
                                <h3>{{ lecture.name }}</h3>
                                <button type="button">강의 보러가기</button>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="buttons">
                <ul>
                    <il>
                        <h3>...이건 내가 아니야... 잘못된게 분명해!</h3>
                        <a href="{% url 'main:index' %}">
                            <button type="button">테스트 다시 하기</button>
                        </a>
                    </il>
                    <il>
                        <h3>다른 사람들은 어떤 유형일까?</h3>
                        <a href="#">
                            <button type="button">다른 결과 알아보기</button>
                        </a>
                    </il>
                    <il>
                        <h3>이런 테스트는 도대체 누가 만든거야? ^0^;;</h3>
                        <a href="#">
                            <button class="color" type="button">제주코딩베이스캠프</button>
                        </a>
                    </il>
                </ul>
            </div>
            <div class="weniv">
                <a href="http://www.paullab.co.kr">
                    <img src="{% static 'image/weniv_logo_purple.png' %}" alt="weniv">
                </a>
                <p>
                    ※ 본 서비스 내 이미지 및 콘텐츠의 저작권은 주식회사 위니브에 있습니다.<br>
                    수정 및 재배포, 무단 도용 시 법적인 문제가 발생할 수 있습니다.
                </p>
            </div>
        </div>
    </section>
{% endblock body %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
    <script type="text/javascript" src="{% static 'js/result.js' %}"></script>
{% endblock js %}

mbit(3주차~)/backend/mbitTest/main/templates/main/result_back.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>result</title>
</head>
<body>
    <h1>결과 페이지</h1>
    <p>{{ developer.name }}</p>
    <img src = "{% static 'image/' %}{{ developer.pk }}.png" width="300"/>
    <a href='/'>메인화면</a>
    <a href="/form">다시하기</a>
</body>
</html>

mbit(3주차~)/backend/mbitTest/main/templates/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/result.css' %}">
    <title>나의 개발 유형찾기</title>
</head>
<body>
    <section id="main_contents">
        <div class="wrapper">
            <div class="result">
                <div class="titles">
                    <h3>예술적 감각이 뛰어난 당신은!</h3>
                    <h1>{{ developer.name }}</h1>
                </div>
                <div class="result_img">
                    <img src="{% static 'img/' %}{{ developer.pk }}.png" alt="frontend">
                </div>
            </div>
            <div class="result_explains">
                <div class="explain">
                    <h3 class="title">나와 맞는 개발 유형은 {{ developer.name }}?!</h3>
                    <ul>
                        <li>
                            프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                        </li>
                        <li>
                            프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                        </li>
                        <li>
                            프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                        </li>
                        <li>
                            프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                        </li>
                    </ul>
                </div>
                <div class="explain">
                    <h3 class="title">Front-end 개발자가 뭐지?</h3>
                    <ul>
                        <li>
                            프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                        </li>
                        <li>
                            프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                        </li>
                        <li>
                            프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                        </li>
                        <li>
                            프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                        </li>
                    </ul>
                </div>
                <div class="explain">
                    <h3 class="title">그래서 어떤 언어부터 공부해야 할까?</h3>
                    <ul class="language_lists">
                        <li>
                            <div class="img_wrap">
                                <img src="{% static 'img/html.png' %}" alt="html">
                            </div>
                            <h3>HTML</h3>
                        </li>
                        <li>
                            <div class="img_wrap">
                                <img src="{% static 'img/css.png' %}" alt="css">
                            </div>
                            <h3>CSS</h3>
                        </li>
                        <li>
                            <div class="img_wrap">
                                <img src="{% static 'img/js.png' %}" alt="javascript">
                            </div>
                            <h3>JavaScript</h3>
                        </li>
                    </ul>
                    <p>
                        프론트엔드는 어쩌고 저쩌고 이기 때문에 기본적으로 무엇을 그렇기 때문에 HTML,CSS를 공부하고 JS를 어쩌고 하는 것이 좋아!
                    </p>
                </div>
            </div>
            <div class="lectures">
                <h3 class="title">강의 추천</h3>                
                <p>Front-end 공부를 시작하기 좋은 강의를 추천해 드릴게요!</p>
                <ul>
                    <li>
                        <img src="{% static 'img/lec_30minutes.png' %}" alt="30분 요약강좌">
                        <h3>HTML, CSS, JS, Python 30분 요약강좌</h3>
                        <a href="https://www.inflearn.com/course/제주코딩-웹개발-30분요약" target="_blank">
                            <button type="button">강의 보러가기</button>
                        </a>
                    </li>
                    <li>
                        <img src="{% static 'img/lec_web_fullstack.png' %}" alt="코알못에서 웹서비스 런칭까지">
                        <h3>코알못에서 웹서비스 런칭까지 : 제주 코딩 베이스캠프(Django)</h3>
                        <a href="https://www.inflearn.com/course/web_fullstack" target="_blank">
                            <button type="button">강의 보러가기</button>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="buttons">
                <ul>
                    <il>
                        <h3>...이건 내가 아니야... 잘못된게 분명해!</h3>
                        <a href="/">
                            <button type="button">테스트 다시 하기</button>
                        </a>
                    </il>
                    <il>
                        <h3>다른 사람들은 어떤 유형일까?</h3>
                        <a href="#">
                            <button type="button">다른 결과 알아보기</button>
                        </a>
                    </il>
                    <il>
                        <h3>이런 테스트는 도대체 누가 만든거야? ^0^;;</h3>
                        <a href="#">
                            <button class="color" type="button">제주코딩베이스캠프</button>
                        </a>
                    </il>
                </ul>
            </div>
            <div class="weniv">
                <a href="http://www.paullab.co.kr">
                    <img src="{% static 'img/weniv_logo_purple.png' %}" alt="weniv">
                </a>
                <p>
                    ※ 본 서비스 내 이미지 및 콘텐츠의 저작권은 주식회사 위니브에 있습니다.<br>
                    수정 및 재배포, 무단 도용 시 법적인 문제가 발생할 수 있습니다.
                </p>
            </div>
        </div>
    </section>
</body>
</html>

mbit(3주차~)/backend/mbitTest/main/templates/result_back.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>result</title>
</head>
<body>
  <h1>결과 페이지</h1>
  <p>{{ developer.name }}</p>
  <a href='/'>메인화면</a>
  <a href="/form">다시하기</a>
</body>
</html>